version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'pg_socketio'
    environment:
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5432:5432'
  redis:
    image: 'redis' 
    container_name: 'rd_socketio'
    ports: 
      - '6379:6379'